Feat/billing
JustShip/justshipto_core pull request #41
Opened 2021-10-05 23:17 UTC by lugodev

2021-10-05 23:51 UTC, ragnarok22 requested changes

2021-10-05 23:51 UTC, ragnarok22 commented on justship/apps/billing/models.py
> +        ('cancelled', 'Cancelled')
Esto aquí debe estar en Español, la segunda opción

2021-10-05 23:51 UTC, ragnarok22 commented on justship/apps/billing/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
en vez de usar User usar la función `django.contrib.auth.get_user_model`

2021-10-06 16:36 UTC, lugodev commented on justship/apps/billing/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
Excelente, me encantó eso! :clap:

2021-10-06 16:43 UTC, merged

2021-10-06 19:55 UTC, ragnarok22 reviewed
well done!